### ISSUE TITLE
cannot find GOROOT directory

### ISSUE THREAD

**Issue by hazcod** [bobheadxi/gobenchdata#42]
GitHub Action complains: `go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.14.1/x64`.
Log:
```
2020-06-22T13:06:46.8623176Z ========================
2020-06-22T13:06:46.8626203Z /bin/gobenchdata
2020-06-22T13:06:46.8631710Z gobenchdata version unknown
2020-06-22T13:06:46.8654639Z INPUT_GO_BENCHMARKS=.
2020-06-22T13:06:46.8655465Z INPUT_GO_TEST_FLAGS=-cpu 1,2
2020-06-22T13:06:46.8655599Z INPUT_PUBLISH_BRANCH=dev
2020-06-22T13:06:46.8655716Z INPUT_PRUNE_COUNT=30
2020-06-22T13:06:46.8655836Z INPUT_CHECKS_CONFIG=.github/gobench.yml
2020-06-22T13:06:46.8655952Z INPUT_SUBDIRECTORY=.
2020-06-22T13:06:46.8656066Z INPUT_CHECKS=true
2020-06-22T13:06:46.8656328Z INPUT_PUBLISH_REPO=ironpeakservices/micro-domain
2020-06-22T13:06:46.8656458Z INPUT_GIT_COMMIT_MESSAGE=chore: add new benchmark
2020-06-22T13:06:46.8656576Z INPUT_PUBLISH=true
2020-06-22T13:06:46.8656689Z INPUT_GO_TEST_PKGS=./...
2020-06-22T13:06:46.8656798Z INPUT_BENCHMARKS_OUT=.github/benchmarks.json
2020-06-22T13:06:46.8658780Z GITHUB_ACTOR=hazcod
2020-06-22T13:06:46.8658913Z GITHUB_WORKSPACE=/github/workspace
2020-06-22T13:06:46.8659367Z GITHUB_REPOSITORY=ironpeakservices/micro-domain
2020-06-22T13:06:46.8659496Z GITHUB_SHA=90100fcb04f70612ac97ed374841de48e4d279df
2020-06-22T13:06:46.8659619Z GITHUB_REF=refs/pull/690/merge
2020-06-22T13:06:46.8659747Z ========================
2020-06-22T13:06:46.8701051Z 
2020-06-22T13:06:46.8702245Z 📊 Running benchmarks...
2020-06-22T13:06:46.8754991Z go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.14.1/x64
2020-06-22T13:06:46.8786763Z detected 0 benchmark suites
2020-06-22T13:06:46.8791656Z successfully output results as json to '/tmp/gobenchdata/benchmarks.json'
2020-06-22T13:06:46.8801012Z 
2020-06-22T13:06:46.8803094Z 📚 Checking out ironpeakservices/micro-domain@dev...
2020-06-22T13:06:46.8813842Z Cloning into '.'...
2020-06-22T13:06:48.0722298Z Switched to a new branch 'dev'
2020-06-22T13:06:48.0728086Z Branch 'dev' set up to track remote branch 'dev' from 'origin'.
2020-06-22T13:06:48.0728191Z 
2020-06-22T13:06:48.0728784Z 🔎 Evaluating results against base runs...
2020-06-22T13:06:48.0803675Z panic: unexpected end of JSON input
2020-06-22T13:06:48.0803787Z 
2020-06-22T13:06:48.0803903Z goroutine 1 [running]:
2020-06-22T13:06:48.0804030Z main.load(0xc0000bfde8, 0x2, 0x2, 0x0, 0x0, 0x0)
2020-06-22T13:06:48.0804461Z 	/tmp/build/io.go:143 +0x275
2020-06-22T13:06:48.0804566Z main.main()
2020-06-22T13:06:48.0804713Z 	/tmp/build/main.go:162 +0xb4d
```

**Comment by bobheadxi** [comment]
@hazcod can you clarify?

**Comment by hazcod** [comment]
Ah, sorry, I mistakingly created this issue instead of keeping it open.
I'm debuggin an issue where no bench suites are detected while `go test -bench . ./...` works. Will update.

**Comment by bobheadxi** [comment]
Interesting - can I see your action configuration, and maybe a line or two of your benchmark data (if that's possible)?

**Comment by bobheadxi** [comment]
@hazcod to clarify - is this the GitHub Action, or running the entrypoint script directly?

**Comment by hazcod** [comment]
Closing it for now, will focus on the other approach.
(I used it via the Action)
