### ISSUE TITLE
on wsl a panic is thrown due to missing dep: xdg-open

### ISSUE THREAD

**Issue by diginicho** [bobheadxi/gobenchdata#79]
```
panic: exec: "xdg-open": executable file not found in $PATH

goroutine 6 [running]:
go.bobheadxi.dev/gobenchdata/internal.OpenBrowser({0xc000028348?, 0x0?})
        /go/pkg/mod/go.bobheadxi.dev/gobenchdata@v1.3.1/internal/browser.go:23 +0x65
created by main.main in goroutine 1
        /go/pkg/mod/go.bobheadxi.dev/gobenchdata@v1.3.1/main.go:140 +0x2ed
```

Windows Sub Linux 2

**Comment by diginicho** [comment]
Solved by using: https://github.com/cpbotha/xdg-open-wsl
